### ISSUE TITLE
Font screenshot

### ISSUE THREAD

**Issue by richellyitalo** [fnky/behave-theme#15]
What is the font used in the screenshot?

**Comment by fnky** [comment]
Either Input or Panic's Coda app monospace font.

**Comment by richellyitalo** [comment]
Thank you.

**Comment by richellyitalo** [comment]
I've found.
"DeJaVu Sans Mono"

**Comment by fnky** [comment]
Panic Sans is the name of Coda monospace font and Input is a font that you can generate or download preset fonts from [their website](http://input.fontbureau.com).

**Comment by richellyitalo** [comment]
Nice bro!
Thank you! Again.
